# Generated by Django 4.1.4 on 2022-12-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanbanApp', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='in_progress',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
