# Generated by Django 4.1.4 on 2022-12-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KanbanApp', '0003_todo_in_progress_alter_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
